using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DesignPatterns.Strategy
{
    public class Employee
    {
        public ExportData CalculatePay()
        {
            ExportData data = new ExportData();

            // Big algorithm to calculate pay
            // ...
            // ...
            // ...
            // ...
            // ...
            // ...
            // ...

            return data;
        }

        public ExportData CalculatePayWithoutOvertime()
        {
            ExportData data = new ExportData();

            // Duplicated algorithm to calculate pay without overtime
            // ...
            // ...
            // ...
            // ...
            // ...
            // ...
            // ...

            return data;
        }

        public ExportData CalculatePayWithoutHolidays()
        {
            ExportData data = new ExportData();

            // Duplicated algorithm to calculate pay without holidays
            // ...
            // ...
            // ...
            // ...
            // ...
            // ...
            // ...

            return data;
        }
   
        public ExportData CalculatePayPerMonth()
        {
            ExportData data = new ExportData();

            // Duplicated algorithm to calculate pay per month
            // ...
            // ...
            // ...
            // ...
            // ...
            // ...
            // ...

            return data;
        }
    }
}
